name: vnote2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  uuid: ^4.2.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: any
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.0
  flutter_quill: ^11.5.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  flutter_quill_extensions: ^11.0.0
  home_widget: ^0.9.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
